<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit40b93c764ded5b2d0d3474144c0a0940
{
    public static $files = array (
        '49a1299791c25c6fd83542c6fedacddd' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/load-v4p11.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stonewallgroup\\SwgDownloads\\' => 28,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stonewallgroup\\SwgDownloads\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit40b93c764ded5b2d0d3474144c0a0940::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit40b93c764ded5b2d0d3474144c0a0940::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit40b93c764ded5b2d0d3474144c0a0940::$classMap;

        }, null, ClassLoader::class);
    }
}
